-- Mandiri News Intelligence App
-- Run this file before rls_policies.sql and seed_data.sql.

create extension if not exists pgcrypto;

create table if not exists public.sources (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  url text,
  country text,
  created_at timestamptz not null default now(),
  constraint sources_name_unique unique (name)
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  created_at timestamptz not null default now(),
  constraint categories_name_unique unique (name)
);

create table if not exists public.articles (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  content text not null default '',
  url text not null,
  image_url text,
  source_id uuid references public.sources(id) on delete set null,
  category_id uuid references public.categories(id) on delete set null,
  published_at timestamptz not null,
  status text not null default 'published',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint articles_url_unique unique (url),
  constraint articles_status_check
    check (status in ('draft', 'published', 'archived'))
);

create table if not exists public.article_analysis (
  id uuid primary key default gen_random_uuid(),
  article_id uuid not null references public.articles(id) on delete cascade,
  summary text,
  sentiment text,
  sentiment_score numeric(6, 5),
  topic text,
  keywords text[] not null default '{}',
  created_at timestamptz not null default now(),
  constraint article_analysis_article_unique unique (article_id),
  constraint article_analysis_sentiment_check
    check (sentiment is null or sentiment in ('positive', 'neutral', 'negative')),
  constraint article_analysis_score_check
    check (
      sentiment_score is null
      or sentiment_score between -1 and 1
    )
);

create table if not exists public.bookmarks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  article_id uuid not null references public.articles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint bookmarks_user_article_unique unique (user_id, article_id)
);

create table if not exists public.reading_history (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  article_id uuid not null references public.articles(id) on delete cascade,
  read_at timestamptz not null default now(),
  constraint reading_history_user_article_unique unique (user_id, article_id)
);

create table if not exists public.user_preferences (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  preferred_category_id uuid references public.categories(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_preferences_user_unique unique (user_id)
);

create index if not exists articles_published_at_idx
  on public.articles (published_at desc);
create index if not exists articles_status_idx
  on public.articles (status);
create index if not exists articles_category_id_idx
  on public.articles (category_id);
create index if not exists articles_source_id_idx
  on public.articles (source_id);
create index if not exists article_analysis_topic_idx
  on public.article_analysis (topic);
create index if not exists article_analysis_keywords_gin_idx
  on public.article_analysis using gin (keywords);
create index if not exists bookmarks_user_id_idx
  on public.bookmarks (user_id);
create index if not exists reading_history_user_read_at_idx
  on public.reading_history (user_id, read_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists articles_set_updated_at on public.articles;
create trigger articles_set_updated_at
before update on public.articles
for each row execute function public.set_updated_at();

drop trigger if exists user_preferences_set_updated_at
  on public.user_preferences;
create trigger user_preferences_set_updated_at
before update on public.user_preferences
for each row execute function public.set_updated_at();

comment on table public.articles is
  'Normalized news articles loaded only by trusted backend processes.';
comment on table public.article_analysis is
  'NLP outputs generated by the Python data pipeline.';
comment on table public.reading_history is
  'One row per user/article; upsert read_at when an article is reopened.';
